### ISSUE TITLE
some feedbacks

### ISSUE THREAD

**Issue by Adafede** [gnames/gndiff#12]
Hi, I tested quickly your tool and here is what I can say:

- Installation works fine
- Commands are clear and consistent with other GNtools
- Adding headers to csv/tsv format would be nice (found them via `-f pretty`)
- The `family` column in the output is quite cryptic for external users, a brief description in the README would probably help.
- The error message ```FATA[0000] the CSV file needs `scientifiName` field``` contains typos
- Globally, very nice even if I don't see applications at the moment on my side, adding somehow a more straightforward way for the user to do `gnfinder` and then `gndiff` on files might open possibilities. I am sure you already had this in mind but I see this combination as very powerful in the future.

Your work is amazing and useful to so many people out there!

**Comment by dimus** [comment]
Thanks a lot @Adafede for your feedback and the typo fix! I made fixes that you suggested. The header was already fixed in https://github.com/gnames/gndiff/issues/10, just did not percolate to a release yet, will be there soon.

**Comment by Adafede** [comment]
Superfast as always!

I might have still not fully understood it, but regarding the `family` column I meant the one in the output... I have plenty of `id clean` and `family clean`associated with the `referenceRecords` ... and nothing if the fields are not clean? Is this expected? What does this `id clean `and `family clean` mean?
